wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1703457609.484047
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      3:
      - 23
      4: 3.9.16
      5: 0.13.10
      6: 4.29.2
      8:
      - 3
      - 5
